### ISSUE TITLE
Redshift tutorial links to s3 demo file with bad permissions that don't allow access

### ISSUE THREAD

**Issue by chrisdag** [awsdocs/amazon-redshift-developer-guide#17] opened 2019-10-16 17:18 UTC
amazon-redshift-developer-guide/doc_source/tutorial-loading-data-download-files.md links to this URL: https://s3.amazonaws.com/awssampledb/LoadingDataSampleFiles.zip

... as part of the Tutorial. However the s3 download .zip file has file level or bucket level permissions that do not allow for the sample files to be downloaded.

**Comment by mjalkio** [comment] 2019-10-20 20:25
I think this is a duplicate of #16.

**Comment by keithhc2** [comment] 2022-07-28 23:55
It looks like the file downloads fine now, so I'm closing this issue.

**Closed as completed by keithhc2** 2022-07-28 23:55 UTC
